name: seisflows
channels:
    - conda-forge
dependencies:
    - pip
    - numpy<2.0.0  # requires PyASDF update
    - obspy
    - cartopy
    - pyyaml
    - pypdf
    - pip:
      - pyatoa
      - pysep-adjtomo
      - -e .

